<?php

/**
 * @file
 * Primary module hooks for Moneris Checkout (MCO) module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_moneris_checkout_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.commerce_moneris_checkout') {
    $text = file_get_contents(__DIR__ . '/README.md');
    if (!Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
      $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
      $parser = $parser_manager->getDefaultParser([
        'render_strategy' => ['type' => 'none'],
      ]);
      return $parser->parse($text);
    }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function commerce_moneris_checkout_theme($existing, $type, $theme, $path) {
  return [
    'commerce_moneris_checkout' => [
      'variables' => [
        'height' => NULL,
        'width' => NULL,
      ],
    ],
  ];
}
